language: python
python:
  - "3.6"
env:
  - PYTHONPATH=`pwd`
install:
  - pip install -r requirements-dev.txt -r requirements.txt
script:
  - ./linters.sh && pytest tests/ --cov=luckycharms/ --cov-report term-missing
after_success:
  - coveralls
